// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'errors.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageError`

@freezed
sealed class DepositClaimError with _$DepositClaimError {
  const DepositClaimError._();

  const factory DepositClaimError.depositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt actualFee,
  }) = DepositClaimError_DepositClaimFeeExceeded;
  const factory DepositClaimError.missingUtxo({required String tx, required int vout}) =
      DepositClaimError_MissingUtxo;
  const factory DepositClaimError.generic({required String message}) = DepositClaimError_Generic;
}

@freezed
sealed class SdkError with _$SdkError implements FrbException {
  const SdkError._();

  const factory SdkError.sparkError(String field0) = SdkError_SparkError;
  const factory SdkError.invalidUuid(String field0) = SdkError_InvalidUuid;
  const factory SdkError.invalidInput(String field0) = SdkError_InvalidInput;
  const factory SdkError.networkError(String field0) = SdkError_NetworkError;
  const factory SdkError.storageError(String field0) = SdkError_StorageError;
  const factory SdkError.chainServiceError(String field0) = SdkError_ChainServiceError;
  const factory SdkError.depositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt actualFee,
  }) = SdkError_DepositClaimFeeExceeded;
  const factory SdkError.missingUtxo({required String tx, required int vout}) = SdkError_MissingUtxo;
  const factory SdkError.lnurlError(String field0) = SdkError_LnurlError;
  const factory SdkError.generic(String field0) = SdkError_Generic;
}
