// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BindingEventListener`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

@freezed
sealed class SdkEvent with _$SdkEvent {
  const SdkEvent._();

  const factory SdkEvent.synced() = SdkEvent_Synced;
  const factory SdkEvent.dataSynced({required bool didPullNewRecords}) = SdkEvent_DataSynced;
  const factory SdkEvent.unclaimedDeposits({required List<DepositInfo> unclaimedDeposits}) =
      SdkEvent_UnclaimedDeposits;
  const factory SdkEvent.claimedDeposits({required List<DepositInfo> claimedDeposits}) =
      SdkEvent_ClaimedDeposits;
  const factory SdkEvent.paymentSucceeded({required Payment payment}) = SdkEvent_PaymentSucceeded;
  const factory SdkEvent.paymentFailed({required Payment payment}) = SdkEvent_PaymentFailed;
}
