// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'errors.dart';
import 'events.dart';
import 'frb_generated.dart';
import 'issuer.dart';
import 'logger.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'sdk.dart';
import 'sdk_builder.dart';

abstract class BreezSdkSparkLibApiImplPlatform extends BaseApiImpl<BreezSdkSparkLibWire> {
  BreezSdkSparkLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BreezSdkPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdkPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SdkBuilderPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilderPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TokenIssuerPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuerPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BreezSdk dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    dynamic raw,
  );

  @protected
  SdkBuilder dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    dynamic raw,
  );

  @protected
  TokenIssuer dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    dynamic raw,
  );

  @protected
  BreezSdk dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    dynamic raw,
  );

  @protected
  SdkBuilder dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    dynamic raw,
  );

  @protected
  TokenIssuer dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    dynamic raw,
  );

  @protected
  Map<String, TokenBalance> dco_decode_Map_String_token_balance_None(dynamic raw);

  @protected
  BreezSdk dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(dynamic raw);

  @protected
  SdkBuilder dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(dynamic raw);

  @protected
  TokenIssuer dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  RustStreamSink<SdkEvent> dco_decode_StreamSink_sdk_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BigInt dco_decode_U128(dynamic raw);

  @protected
  AesSuccessActionData dco_decode_aes_success_action_data(dynamic raw);

  @protected
  AesSuccessActionDataDecrypted dco_decode_aes_success_action_data_decrypted(dynamic raw);

  @protected
  AesSuccessActionDataResult dco_decode_aes_success_action_data_result(dynamic raw);

  @protected
  Amount dco_decode_amount(dynamic raw);

  @protected
  AssetFilter dco_decode_asset_filter(dynamic raw);

  @protected
  Bip21Details dco_decode_bip_21_details(dynamic raw);

  @protected
  Bip21Extra dco_decode_bip_21_extra(dynamic raw);

  @protected
  BitcoinAddressDetails dco_decode_bitcoin_address_details(dynamic raw);

  @protected
  BitcoinNetwork dco_decode_bitcoin_network(dynamic raw);

  @protected
  Bolt11Invoice dco_decode_bolt_11_invoice(dynamic raw);

  @protected
  Bolt11InvoiceDetails dco_decode_bolt_11_invoice_details(dynamic raw);

  @protected
  Bolt11RouteHint dco_decode_bolt_11_route_hint(dynamic raw);

  @protected
  Bolt11RouteHintHop dco_decode_bolt_11_route_hint_hop(dynamic raw);

  @protected
  Bolt12Invoice dco_decode_bolt_12_invoice(dynamic raw);

  @protected
  Bolt12InvoiceDetails dco_decode_bolt_12_invoice_details(dynamic raw);

  @protected
  Bolt12InvoiceRequestDetails dco_decode_bolt_12_invoice_request_details(dynamic raw);

  @protected
  Bolt12Offer dco_decode_bolt_12_offer(dynamic raw);

  @protected
  Bolt12OfferBlindedPath dco_decode_bolt_12_offer_blinded_path(dynamic raw);

  @protected
  Bolt12OfferDetails dco_decode_bolt_12_offer_details(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AesSuccessActionData dco_decode_box_autoadd_aes_success_action_data(dynamic raw);

  @protected
  AesSuccessActionDataDecrypted dco_decode_box_autoadd_aes_success_action_data_decrypted(dynamic raw);

  @protected
  AesSuccessActionDataResult dco_decode_box_autoadd_aes_success_action_data_result(dynamic raw);

  @protected
  Amount dco_decode_box_autoadd_amount(dynamic raw);

  @protected
  AssetFilter dco_decode_box_autoadd_asset_filter(dynamic raw);

  @protected
  Bip21Details dco_decode_box_autoadd_bip_21_details(dynamic raw);

  @protected
  BitcoinAddressDetails dco_decode_box_autoadd_bitcoin_address_details(dynamic raw);

  @protected
  Bolt11InvoiceDetails dco_decode_box_autoadd_bolt_11_invoice_details(dynamic raw);

  @protected
  Bolt12InvoiceDetails dco_decode_box_autoadd_bolt_12_invoice_details(dynamic raw);

  @protected
  Bolt12InvoiceRequestDetails dco_decode_box_autoadd_bolt_12_invoice_request_details(dynamic raw);

  @protected
  Bolt12OfferDetails dco_decode_box_autoadd_bolt_12_offer_details(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BurnIssuerTokenRequest dco_decode_box_autoadd_burn_issuer_token_request(dynamic raw);

  @protected
  CheckLightningAddressRequest dco_decode_box_autoadd_check_lightning_address_request(dynamic raw);

  @protected
  CheckMessageRequest dco_decode_box_autoadd_check_message_request(dynamic raw);

  @protected
  ClaimDepositRequest dco_decode_box_autoadd_claim_deposit_request(dynamic raw);

  @protected
  ClaimHtlcPaymentRequest dco_decode_box_autoadd_claim_htlc_payment_request(dynamic raw);

  @protected
  Config dco_decode_box_autoadd_config(dynamic raw);

  @protected
  ConnectRequest dco_decode_box_autoadd_connect_request(dynamic raw);

  @protected
  ConversionEstimate dco_decode_box_autoadd_conversion_estimate(dynamic raw);

  @protected
  ConversionInfo dco_decode_box_autoadd_conversion_info(dynamic raw);

  @protected
  ConversionOptions dco_decode_box_autoadd_conversion_options(dynamic raw);

  @protected
  ConversionPurpose dco_decode_box_autoadd_conversion_purpose(dynamic raw);

  @protected
  CreateIssuerTokenRequest dco_decode_box_autoadd_create_issuer_token_request(dynamic raw);

  @protected
  Credentials dco_decode_box_autoadd_credentials(dynamic raw);

  @protected
  DepositClaimError dco_decode_box_autoadd_deposit_claim_error(dynamic raw);

  @protected
  Fee dco_decode_box_autoadd_fee(dynamic raw);

  @protected
  FetchConversionLimitsRequest dco_decode_box_autoadd_fetch_conversion_limits_request(dynamic raw);

  @protected
  FreezeIssuerTokenRequest dco_decode_box_autoadd_freeze_issuer_token_request(dynamic raw);

  @protected
  GetInfoRequest dco_decode_box_autoadd_get_info_request(dynamic raw);

  @protected
  GetPaymentRequest dco_decode_box_autoadd_get_payment_request(dynamic raw);

  @protected
  GetTokensMetadataRequest dco_decode_box_autoadd_get_tokens_metadata_request(dynamic raw);

  @protected
  KeySetConfig dco_decode_box_autoadd_key_set_config(dynamic raw);

  @protected
  LightningAddressDetails dco_decode_box_autoadd_lightning_address_details(dynamic raw);

  @protected
  LightningAddressInfo dco_decode_box_autoadd_lightning_address_info(dynamic raw);

  @protected
  ListPaymentsRequest dco_decode_box_autoadd_list_payments_request(dynamic raw);

  @protected
  ListUnclaimedDepositsRequest dco_decode_box_autoadd_list_unclaimed_deposits_request(dynamic raw);

  @protected
  LnurlAuthRequestDetails dco_decode_box_autoadd_lnurl_auth_request_details(dynamic raw);

  @protected
  LnurlErrorDetails dco_decode_box_autoadd_lnurl_error_details(dynamic raw);

  @protected
  LnurlPayInfo dco_decode_box_autoadd_lnurl_pay_info(dynamic raw);

  @protected
  LnurlPayRequest dco_decode_box_autoadd_lnurl_pay_request(dynamic raw);

  @protected
  LnurlPayRequestDetails dco_decode_box_autoadd_lnurl_pay_request_details(dynamic raw);

  @protected
  LnurlReceiveMetadata dco_decode_box_autoadd_lnurl_receive_metadata(dynamic raw);

  @protected
  LnurlWithdrawInfo dco_decode_box_autoadd_lnurl_withdraw_info(dynamic raw);

  @protected
  LnurlWithdrawRequest dco_decode_box_autoadd_lnurl_withdraw_request(dynamic raw);

  @protected
  LnurlWithdrawRequestDetails dco_decode_box_autoadd_lnurl_withdraw_request_details(dynamic raw);

  @protected
  MaxFee dco_decode_box_autoadd_max_fee(dynamic raw);

  @protected
  MessageSuccessActionData dco_decode_box_autoadd_message_success_action_data(dynamic raw);

  @protected
  MintIssuerTokenRequest dco_decode_box_autoadd_mint_issuer_token_request(dynamic raw);

  @protected
  OptimizationEvent dco_decode_box_autoadd_optimization_event(dynamic raw);

  @protected
  Payment dco_decode_box_autoadd_payment(dynamic raw);

  @protected
  PaymentDetails dco_decode_box_autoadd_payment_details(dynamic raw);

  @protected
  PrepareLnurlPayRequest dco_decode_box_autoadd_prepare_lnurl_pay_request(dynamic raw);

  @protected
  PrepareSendPaymentRequest dco_decode_box_autoadd_prepare_send_payment_request(dynamic raw);

  @protected
  ReceivePaymentRequest dco_decode_box_autoadd_receive_payment_request(dynamic raw);

  @protected
  RefundDepositRequest dco_decode_box_autoadd_refund_deposit_request(dynamic raw);

  @protected
  RegisterLightningAddressRequest dco_decode_box_autoadd_register_lightning_address_request(dynamic raw);

  @protected
  Seed dco_decode_box_autoadd_seed(dynamic raw);

  @protected
  SendOnchainFeeQuote dco_decode_box_autoadd_send_onchain_fee_quote(dynamic raw);

  @protected
  SendPaymentOptions dco_decode_box_autoadd_send_payment_options(dynamic raw);

  @protected
  SendPaymentRequest dco_decode_box_autoadd_send_payment_request(dynamic raw);

  @protected
  SignMessageRequest dco_decode_box_autoadd_sign_message_request(dynamic raw);

  @protected
  SilentPaymentAddressDetails dco_decode_box_autoadd_silent_payment_address_details(dynamic raw);

  @protected
  SparkAddressDetails dco_decode_box_autoadd_spark_address_details(dynamic raw);

  @protected
  SparkHtlcDetails dco_decode_box_autoadd_spark_htlc_details(dynamic raw);

  @protected
  SparkHtlcOptions dco_decode_box_autoadd_spark_htlc_options(dynamic raw);

  @protected
  SparkInvoiceDetails dco_decode_box_autoadd_spark_invoice_details(dynamic raw);

  @protected
  SparkInvoicePaymentDetails dco_decode_box_autoadd_spark_invoice_payment_details(dynamic raw);

  @protected
  SuccessAction dco_decode_box_autoadd_success_action(dynamic raw);

  @protected
  SuccessActionProcessed dco_decode_box_autoadd_success_action_processed(dynamic raw);

  @protected
  Symbol dco_decode_box_autoadd_symbol(dynamic raw);

  @protected
  SyncWalletRequest dco_decode_box_autoadd_sync_wallet_request(dynamic raw);

  @protected
  TokenMetadata dco_decode_box_autoadd_token_metadata(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UnfreezeIssuerTokenRequest dco_decode_box_autoadd_unfreeze_issuer_token_request(dynamic raw);

  @protected
  UpdateUserSettingsRequest dco_decode_box_autoadd_update_user_settings_request(dynamic raw);

  @protected
  UrlSuccessActionData dco_decode_box_autoadd_url_success_action_data(dynamic raw);

  @protected
  BurnIssuerTokenRequest dco_decode_burn_issuer_token_request(dynamic raw);

  @protected
  ChainApiType dco_decode_chain_api_type(dynamic raw);

  @protected
  CheckLightningAddressRequest dco_decode_check_lightning_address_request(dynamic raw);

  @protected
  CheckMessageRequest dco_decode_check_message_request(dynamic raw);

  @protected
  CheckMessageResponse dco_decode_check_message_response(dynamic raw);

  @protected
  ClaimDepositRequest dco_decode_claim_deposit_request(dynamic raw);

  @protected
  ClaimDepositResponse dco_decode_claim_deposit_response(dynamic raw);

  @protected
  ClaimHtlcPaymentRequest dco_decode_claim_htlc_payment_request(dynamic raw);

  @protected
  ClaimHtlcPaymentResponse dco_decode_claim_htlc_payment_response(dynamic raw);

  @protected
  Config dco_decode_config(dynamic raw);

  @protected
  ConnectRequest dco_decode_connect_request(dynamic raw);

  @protected
  ConversionEstimate dco_decode_conversion_estimate(dynamic raw);

  @protected
  ConversionInfo dco_decode_conversion_info(dynamic raw);

  @protected
  ConversionOptions dco_decode_conversion_options(dynamic raw);

  @protected
  ConversionPurpose dco_decode_conversion_purpose(dynamic raw);

  @protected
  ConversionStatus dco_decode_conversion_status(dynamic raw);

  @protected
  ConversionType dco_decode_conversion_type(dynamic raw);

  @protected
  CreateIssuerTokenRequest dco_decode_create_issuer_token_request(dynamic raw);

  @protected
  Credentials dco_decode_credentials(dynamic raw);

  @protected
  CurrencyInfo dco_decode_currency_info(dynamic raw);

  @protected
  DepositClaimError dco_decode_deposit_claim_error(dynamic raw);

  @protected
  DepositInfo dco_decode_deposit_info(dynamic raw);

  @protected
  ExternalInputParser dco_decode_external_input_parser(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Fee dco_decode_fee(dynamic raw);

  @protected
  FetchConversionLimitsRequest dco_decode_fetch_conversion_limits_request(dynamic raw);

  @protected
  FetchConversionLimitsResponse dco_decode_fetch_conversion_limits_response(dynamic raw);

  @protected
  FiatCurrency dco_decode_fiat_currency(dynamic raw);

  @protected
  FreezeIssuerTokenRequest dco_decode_freeze_issuer_token_request(dynamic raw);

  @protected
  FreezeIssuerTokenResponse dco_decode_freeze_issuer_token_response(dynamic raw);

  @protected
  GetInfoRequest dco_decode_get_info_request(dynamic raw);

  @protected
  GetInfoResponse dco_decode_get_info_response(dynamic raw);

  @protected
  GetPaymentRequest dco_decode_get_payment_request(dynamic raw);

  @protected
  GetPaymentResponse dco_decode_get_payment_response(dynamic raw);

  @protected
  GetTokensMetadataRequest dco_decode_get_tokens_metadata_request(dynamic raw);

  @protected
  GetTokensMetadataResponse dco_decode_get_tokens_metadata_response(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InputType dco_decode_input_type(dynamic raw);

  @protected
  KeySetConfig dco_decode_key_set_config(dynamic raw);

  @protected
  KeySetType dco_decode_key_set_type(dynamic raw);

  @protected
  LightningAddressDetails dco_decode_lightning_address_details(dynamic raw);

  @protected
  LightningAddressInfo dco_decode_lightning_address_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Bip21Extra> dco_decode_list_bip_21_extra(dynamic raw);

  @protected
  List<Bolt11RouteHint> dco_decode_list_bolt_11_route_hint(dynamic raw);

  @protected
  List<Bolt11RouteHintHop> dco_decode_list_bolt_11_route_hint_hop(dynamic raw);

  @protected
  List<Bolt12OfferBlindedPath> dco_decode_list_bolt_12_offer_blinded_path(dynamic raw);

  @protected
  List<DepositInfo> dco_decode_list_deposit_info(dynamic raw);

  @protected
  List<ExternalInputParser> dco_decode_list_external_input_parser(dynamic raw);

  @protected
  ListFiatCurrenciesResponse dco_decode_list_fiat_currencies_response(dynamic raw);

  @protected
  List<FiatCurrency> dco_decode_list_fiat_currency(dynamic raw);

  @protected
  ListFiatRatesResponse dco_decode_list_fiat_rates_response(dynamic raw);

  @protected
  List<InputType> dco_decode_list_input_type(dynamic raw);

  @protected
  List<LocaleOverrides> dco_decode_list_locale_overrides(dynamic raw);

  @protected
  List<LocalizedName> dco_decode_list_localized_name(dynamic raw);

  @protected
  List<Payment> dco_decode_list_payment(dynamic raw);

  @protected
  List<PaymentDetailsFilter> dco_decode_list_payment_details_filter(dynamic raw);

  @protected
  List<PaymentStatus> dco_decode_list_payment_status(dynamic raw);

  @protected
  List<PaymentType> dco_decode_list_payment_type(dynamic raw);

  @protected
  ListPaymentsRequest dco_decode_list_payments_request(dynamic raw);

  @protected
  ListPaymentsResponse dco_decode_list_payments_response(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Rate> dco_decode_list_rate(dynamic raw);

  @protected
  List<(String, TokenBalance)> dco_decode_list_record_string_token_balance(dynamic raw);

  @protected
  List<SparkHtlcStatus> dco_decode_list_spark_htlc_status(dynamic raw);

  @protected
  List<TokenMetadata> dco_decode_list_token_metadata(dynamic raw);

  @protected
  ListUnclaimedDepositsRequest dco_decode_list_unclaimed_deposits_request(dynamic raw);

  @protected
  ListUnclaimedDepositsResponse dco_decode_list_unclaimed_deposits_response(dynamic raw);

  @protected
  LnurlAuthRequestDetails dco_decode_lnurl_auth_request_details(dynamic raw);

  @protected
  LnurlCallbackStatus dco_decode_lnurl_callback_status(dynamic raw);

  @protected
  LnurlErrorDetails dco_decode_lnurl_error_details(dynamic raw);

  @protected
  LnurlPayInfo dco_decode_lnurl_pay_info(dynamic raw);

  @protected
  LnurlPayRequest dco_decode_lnurl_pay_request(dynamic raw);

  @protected
  LnurlPayRequestDetails dco_decode_lnurl_pay_request_details(dynamic raw);

  @protected
  LnurlPayResponse dco_decode_lnurl_pay_response(dynamic raw);

  @protected
  LnurlReceiveMetadata dco_decode_lnurl_receive_metadata(dynamic raw);

  @protected
  LnurlWithdrawInfo dco_decode_lnurl_withdraw_info(dynamic raw);

  @protected
  LnurlWithdrawRequest dco_decode_lnurl_withdraw_request(dynamic raw);

  @protected
  LnurlWithdrawRequestDetails dco_decode_lnurl_withdraw_request_details(dynamic raw);

  @protected
  LnurlWithdrawResponse dco_decode_lnurl_withdraw_response(dynamic raw);

  @protected
  LocaleOverrides dco_decode_locale_overrides(dynamic raw);

  @protected
  LocalizedName dco_decode_localized_name(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  MaxFee dco_decode_max_fee(dynamic raw);

  @protected
  MessageSuccessActionData dco_decode_message_success_action_data(dynamic raw);

  @protected
  MintIssuerTokenRequest dco_decode_mint_issuer_token_request(dynamic raw);

  @protected
  Network dco_decode_network(dynamic raw);

  @protected
  OnchainConfirmationSpeed dco_decode_onchain_confirmation_speed(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_U128(dynamic raw);

  @protected
  Amount? dco_decode_opt_box_autoadd_amount(dynamic raw);

  @protected
  AssetFilter? dco_decode_opt_box_autoadd_asset_filter(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ConversionEstimate? dco_decode_opt_box_autoadd_conversion_estimate(dynamic raw);

  @protected
  ConversionInfo? dco_decode_opt_box_autoadd_conversion_info(dynamic raw);

  @protected
  ConversionOptions? dco_decode_opt_box_autoadd_conversion_options(dynamic raw);

  @protected
  ConversionPurpose? dco_decode_opt_box_autoadd_conversion_purpose(dynamic raw);

  @protected
  Credentials? dco_decode_opt_box_autoadd_credentials(dynamic raw);

  @protected
  DepositClaimError? dco_decode_opt_box_autoadd_deposit_claim_error(dynamic raw);

  @protected
  Fee? dco_decode_opt_box_autoadd_fee(dynamic raw);

  @protected
  LightningAddressInfo? dco_decode_opt_box_autoadd_lightning_address_info(dynamic raw);

  @protected
  LnurlPayInfo? dco_decode_opt_box_autoadd_lnurl_pay_info(dynamic raw);

  @protected
  LnurlReceiveMetadata? dco_decode_opt_box_autoadd_lnurl_receive_metadata(dynamic raw);

  @protected
  LnurlWithdrawInfo? dco_decode_opt_box_autoadd_lnurl_withdraw_info(dynamic raw);

  @protected
  MaxFee? dco_decode_opt_box_autoadd_max_fee(dynamic raw);

  @protected
  Payment? dco_decode_opt_box_autoadd_payment(dynamic raw);

  @protected
  PaymentDetails? dco_decode_opt_box_autoadd_payment_details(dynamic raw);

  @protected
  SendPaymentOptions? dco_decode_opt_box_autoadd_send_payment_options(dynamic raw);

  @protected
  SparkHtlcDetails? dco_decode_opt_box_autoadd_spark_htlc_details(dynamic raw);

  @protected
  SparkHtlcOptions? dco_decode_opt_box_autoadd_spark_htlc_options(dynamic raw);

  @protected
  SparkInvoicePaymentDetails? dco_decode_opt_box_autoadd_spark_invoice_payment_details(dynamic raw);

  @protected
  SuccessAction? dco_decode_opt_box_autoadd_success_action(dynamic raw);

  @protected
  SuccessActionProcessed? dco_decode_opt_box_autoadd_success_action_processed(dynamic raw);

  @protected
  Symbol? dco_decode_opt_box_autoadd_symbol(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<ExternalInputParser>? dco_decode_opt_list_external_input_parser(dynamic raw);

  @protected
  List<PaymentDetailsFilter>? dco_decode_opt_list_payment_details_filter(dynamic raw);

  @protected
  List<PaymentStatus>? dco_decode_opt_list_payment_status(dynamic raw);

  @protected
  List<PaymentType>? dco_decode_opt_list_payment_type(dynamic raw);

  @protected
  List<SparkHtlcStatus>? dco_decode_opt_list_spark_htlc_status(dynamic raw);

  @protected
  OptimizationConfig dco_decode_optimization_config(dynamic raw);

  @protected
  OptimizationEvent dco_decode_optimization_event(dynamic raw);

  @protected
  OptimizationProgress dco_decode_optimization_progress(dynamic raw);

  @protected
  Payment dco_decode_payment(dynamic raw);

  @protected
  PaymentDetails dco_decode_payment_details(dynamic raw);

  @protected
  PaymentDetailsFilter dco_decode_payment_details_filter(dynamic raw);

  @protected
  PaymentMethod dco_decode_payment_method(dynamic raw);

  @protected
  PaymentRequestSource dco_decode_payment_request_source(dynamic raw);

  @protected
  PaymentStatus dco_decode_payment_status(dynamic raw);

  @protected
  PaymentType dco_decode_payment_type(dynamic raw);

  @protected
  PrepareLnurlPayRequest dco_decode_prepare_lnurl_pay_request(dynamic raw);

  @protected
  PrepareLnurlPayResponse dco_decode_prepare_lnurl_pay_response(dynamic raw);

  @protected
  PrepareSendPaymentRequest dco_decode_prepare_send_payment_request(dynamic raw);

  @protected
  PrepareSendPaymentResponse dco_decode_prepare_send_payment_response(dynamic raw);

  @protected
  Rate dco_decode_rate(dynamic raw);

  @protected
  ReceivePaymentMethod dco_decode_receive_payment_method(dynamic raw);

  @protected
  ReceivePaymentRequest dco_decode_receive_payment_request(dynamic raw);

  @protected
  ReceivePaymentResponse dco_decode_receive_payment_response(dynamic raw);

  @protected
  RecommendedFees dco_decode_recommended_fees(dynamic raw);

  @protected
  (String, TokenBalance) dco_decode_record_string_token_balance(dynamic raw);

  @protected
  RefundDepositRequest dco_decode_refund_deposit_request(dynamic raw);

  @protected
  RefundDepositResponse dco_decode_refund_deposit_response(dynamic raw);

  @protected
  RegisterLightningAddressRequest dco_decode_register_lightning_address_request(dynamic raw);

  @protected
  SdkError dco_decode_sdk_error(dynamic raw);

  @protected
  SdkEvent dco_decode_sdk_event(dynamic raw);

  @protected
  Seed dco_decode_seed(dynamic raw);

  @protected
  SendOnchainFeeQuote dco_decode_send_onchain_fee_quote(dynamic raw);

  @protected
  SendOnchainSpeedFeeQuote dco_decode_send_onchain_speed_fee_quote(dynamic raw);

  @protected
  SendPaymentMethod dco_decode_send_payment_method(dynamic raw);

  @protected
  SendPaymentOptions dco_decode_send_payment_options(dynamic raw);

  @protected
  SendPaymentRequest dco_decode_send_payment_request(dynamic raw);

  @protected
  SendPaymentResponse dco_decode_send_payment_response(dynamic raw);

  @protected
  SignMessageRequest dco_decode_sign_message_request(dynamic raw);

  @protected
  SignMessageResponse dco_decode_sign_message_response(dynamic raw);

  @protected
  SilentPaymentAddressDetails dco_decode_silent_payment_address_details(dynamic raw);

  @protected
  SparkAddressDetails dco_decode_spark_address_details(dynamic raw);

  @protected
  SparkHtlcDetails dco_decode_spark_htlc_details(dynamic raw);

  @protected
  SparkHtlcOptions dco_decode_spark_htlc_options(dynamic raw);

  @protected
  SparkHtlcStatus dco_decode_spark_htlc_status(dynamic raw);

  @protected
  SparkInvoiceDetails dco_decode_spark_invoice_details(dynamic raw);

  @protected
  SparkInvoicePaymentDetails dco_decode_spark_invoice_payment_details(dynamic raw);

  @protected
  SuccessAction dco_decode_success_action(dynamic raw);

  @protected
  SuccessActionProcessed dco_decode_success_action_processed(dynamic raw);

  @protected
  Symbol dco_decode_symbol(dynamic raw);

  @protected
  SyncWalletRequest dco_decode_sync_wallet_request(dynamic raw);

  @protected
  SyncWalletResponse dco_decode_sync_wallet_response(dynamic raw);

  @protected
  TokenBalance dco_decode_token_balance(dynamic raw);

  @protected
  TokenMetadata dco_decode_token_metadata(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UnfreezeIssuerTokenRequest dco_decode_unfreeze_issuer_token_request(dynamic raw);

  @protected
  UnfreezeIssuerTokenResponse dco_decode_unfreeze_issuer_token_response(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateUserSettingsRequest dco_decode_update_user_settings_request(dynamic raw);

  @protected
  UrlSuccessActionData dco_decode_url_success_action_data(dynamic raw);

  @protected
  UserSettings dco_decode_user_settings(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BreezSdk sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    SseDeserializer deserializer,
  );

  @protected
  SdkBuilder sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SseDeserializer deserializer,
  );

  @protected
  TokenIssuer sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    SseDeserializer deserializer,
  );

  @protected
  BreezSdk sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    SseDeserializer deserializer,
  );

  @protected
  SdkBuilder sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SseDeserializer deserializer,
  );

  @protected
  TokenIssuer sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, TokenBalance> sse_decode_Map_String_token_balance_None(SseDeserializer deserializer);

  @protected
  BreezSdk sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    SseDeserializer deserializer,
  );

  @protected
  SdkBuilder sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SseDeserializer deserializer,
  );

  @protected
  TokenIssuer sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SdkEvent> sse_decode_StreamSink_sdk_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer);

  @protected
  AesSuccessActionData sse_decode_aes_success_action_data(SseDeserializer deserializer);

  @protected
  AesSuccessActionDataDecrypted sse_decode_aes_success_action_data_decrypted(SseDeserializer deserializer);

  @protected
  AesSuccessActionDataResult sse_decode_aes_success_action_data_result(SseDeserializer deserializer);

  @protected
  Amount sse_decode_amount(SseDeserializer deserializer);

  @protected
  AssetFilter sse_decode_asset_filter(SseDeserializer deserializer);

  @protected
  Bip21Details sse_decode_bip_21_details(SseDeserializer deserializer);

  @protected
  Bip21Extra sse_decode_bip_21_extra(SseDeserializer deserializer);

  @protected
  BitcoinAddressDetails sse_decode_bitcoin_address_details(SseDeserializer deserializer);

  @protected
  BitcoinNetwork sse_decode_bitcoin_network(SseDeserializer deserializer);

  @protected
  Bolt11Invoice sse_decode_bolt_11_invoice(SseDeserializer deserializer);

  @protected
  Bolt11InvoiceDetails sse_decode_bolt_11_invoice_details(SseDeserializer deserializer);

  @protected
  Bolt11RouteHint sse_decode_bolt_11_route_hint(SseDeserializer deserializer);

  @protected
  Bolt11RouteHintHop sse_decode_bolt_11_route_hint_hop(SseDeserializer deserializer);

  @protected
  Bolt12Invoice sse_decode_bolt_12_invoice(SseDeserializer deserializer);

  @protected
  Bolt12InvoiceDetails sse_decode_bolt_12_invoice_details(SseDeserializer deserializer);

  @protected
  Bolt12InvoiceRequestDetails sse_decode_bolt_12_invoice_request_details(SseDeserializer deserializer);

  @protected
  Bolt12Offer sse_decode_bolt_12_offer(SseDeserializer deserializer);

  @protected
  Bolt12OfferBlindedPath sse_decode_bolt_12_offer_blinded_path(SseDeserializer deserializer);

  @protected
  Bolt12OfferDetails sse_decode_bolt_12_offer_details(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AesSuccessActionData sse_decode_box_autoadd_aes_success_action_data(SseDeserializer deserializer);

  @protected
  AesSuccessActionDataDecrypted sse_decode_box_autoadd_aes_success_action_data_decrypted(
    SseDeserializer deserializer,
  );

  @protected
  AesSuccessActionDataResult sse_decode_box_autoadd_aes_success_action_data_result(
    SseDeserializer deserializer,
  );

  @protected
  Amount sse_decode_box_autoadd_amount(SseDeserializer deserializer);

  @protected
  AssetFilter sse_decode_box_autoadd_asset_filter(SseDeserializer deserializer);

  @protected
  Bip21Details sse_decode_box_autoadd_bip_21_details(SseDeserializer deserializer);

  @protected
  BitcoinAddressDetails sse_decode_box_autoadd_bitcoin_address_details(SseDeserializer deserializer);

  @protected
  Bolt11InvoiceDetails sse_decode_box_autoadd_bolt_11_invoice_details(SseDeserializer deserializer);

  @protected
  Bolt12InvoiceDetails sse_decode_box_autoadd_bolt_12_invoice_details(SseDeserializer deserializer);

  @protected
  Bolt12InvoiceRequestDetails sse_decode_box_autoadd_bolt_12_invoice_request_details(
    SseDeserializer deserializer,
  );

  @protected
  Bolt12OfferDetails sse_decode_box_autoadd_bolt_12_offer_details(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BurnIssuerTokenRequest sse_decode_box_autoadd_burn_issuer_token_request(SseDeserializer deserializer);

  @protected
  CheckLightningAddressRequest sse_decode_box_autoadd_check_lightning_address_request(
    SseDeserializer deserializer,
  );

  @protected
  CheckMessageRequest sse_decode_box_autoadd_check_message_request(SseDeserializer deserializer);

  @protected
  ClaimDepositRequest sse_decode_box_autoadd_claim_deposit_request(SseDeserializer deserializer);

  @protected
  ClaimHtlcPaymentRequest sse_decode_box_autoadd_claim_htlc_payment_request(SseDeserializer deserializer);

  @protected
  Config sse_decode_box_autoadd_config(SseDeserializer deserializer);

  @protected
  ConnectRequest sse_decode_box_autoadd_connect_request(SseDeserializer deserializer);

  @protected
  ConversionEstimate sse_decode_box_autoadd_conversion_estimate(SseDeserializer deserializer);

  @protected
  ConversionInfo sse_decode_box_autoadd_conversion_info(SseDeserializer deserializer);

  @protected
  ConversionOptions sse_decode_box_autoadd_conversion_options(SseDeserializer deserializer);

  @protected
  ConversionPurpose sse_decode_box_autoadd_conversion_purpose(SseDeserializer deserializer);

  @protected
  CreateIssuerTokenRequest sse_decode_box_autoadd_create_issuer_token_request(SseDeserializer deserializer);

  @protected
  Credentials sse_decode_box_autoadd_credentials(SseDeserializer deserializer);

  @protected
  DepositClaimError sse_decode_box_autoadd_deposit_claim_error(SseDeserializer deserializer);

  @protected
  Fee sse_decode_box_autoadd_fee(SseDeserializer deserializer);

  @protected
  FetchConversionLimitsRequest sse_decode_box_autoadd_fetch_conversion_limits_request(
    SseDeserializer deserializer,
  );

  @protected
  FreezeIssuerTokenRequest sse_decode_box_autoadd_freeze_issuer_token_request(SseDeserializer deserializer);

  @protected
  GetInfoRequest sse_decode_box_autoadd_get_info_request(SseDeserializer deserializer);

  @protected
  GetPaymentRequest sse_decode_box_autoadd_get_payment_request(SseDeserializer deserializer);

  @protected
  GetTokensMetadataRequest sse_decode_box_autoadd_get_tokens_metadata_request(SseDeserializer deserializer);

  @protected
  KeySetConfig sse_decode_box_autoadd_key_set_config(SseDeserializer deserializer);

  @protected
  LightningAddressDetails sse_decode_box_autoadd_lightning_address_details(SseDeserializer deserializer);

  @protected
  LightningAddressInfo sse_decode_box_autoadd_lightning_address_info(SseDeserializer deserializer);

  @protected
  ListPaymentsRequest sse_decode_box_autoadd_list_payments_request(SseDeserializer deserializer);

  @protected
  ListUnclaimedDepositsRequest sse_decode_box_autoadd_list_unclaimed_deposits_request(
    SseDeserializer deserializer,
  );

  @protected
  LnurlAuthRequestDetails sse_decode_box_autoadd_lnurl_auth_request_details(SseDeserializer deserializer);

  @protected
  LnurlErrorDetails sse_decode_box_autoadd_lnurl_error_details(SseDeserializer deserializer);

  @protected
  LnurlPayInfo sse_decode_box_autoadd_lnurl_pay_info(SseDeserializer deserializer);

  @protected
  LnurlPayRequest sse_decode_box_autoadd_lnurl_pay_request(SseDeserializer deserializer);

  @protected
  LnurlPayRequestDetails sse_decode_box_autoadd_lnurl_pay_request_details(SseDeserializer deserializer);

  @protected
  LnurlReceiveMetadata sse_decode_box_autoadd_lnurl_receive_metadata(SseDeserializer deserializer);

  @protected
  LnurlWithdrawInfo sse_decode_box_autoadd_lnurl_withdraw_info(SseDeserializer deserializer);

  @protected
  LnurlWithdrawRequest sse_decode_box_autoadd_lnurl_withdraw_request(SseDeserializer deserializer);

  @protected
  LnurlWithdrawRequestDetails sse_decode_box_autoadd_lnurl_withdraw_request_details(
    SseDeserializer deserializer,
  );

  @protected
  MaxFee sse_decode_box_autoadd_max_fee(SseDeserializer deserializer);

  @protected
  MessageSuccessActionData sse_decode_box_autoadd_message_success_action_data(SseDeserializer deserializer);

  @protected
  MintIssuerTokenRequest sse_decode_box_autoadd_mint_issuer_token_request(SseDeserializer deserializer);

  @protected
  OptimizationEvent sse_decode_box_autoadd_optimization_event(SseDeserializer deserializer);

  @protected
  Payment sse_decode_box_autoadd_payment(SseDeserializer deserializer);

  @protected
  PaymentDetails sse_decode_box_autoadd_payment_details(SseDeserializer deserializer);

  @protected
  PrepareLnurlPayRequest sse_decode_box_autoadd_prepare_lnurl_pay_request(SseDeserializer deserializer);

  @protected
  PrepareSendPaymentRequest sse_decode_box_autoadd_prepare_send_payment_request(SseDeserializer deserializer);

  @protected
  ReceivePaymentRequest sse_decode_box_autoadd_receive_payment_request(SseDeserializer deserializer);

  @protected
  RefundDepositRequest sse_decode_box_autoadd_refund_deposit_request(SseDeserializer deserializer);

  @protected
  RegisterLightningAddressRequest sse_decode_box_autoadd_register_lightning_address_request(
    SseDeserializer deserializer,
  );

  @protected
  Seed sse_decode_box_autoadd_seed(SseDeserializer deserializer);

  @protected
  SendOnchainFeeQuote sse_decode_box_autoadd_send_onchain_fee_quote(SseDeserializer deserializer);

  @protected
  SendPaymentOptions sse_decode_box_autoadd_send_payment_options(SseDeserializer deserializer);

  @protected
  SendPaymentRequest sse_decode_box_autoadd_send_payment_request(SseDeserializer deserializer);

  @protected
  SignMessageRequest sse_decode_box_autoadd_sign_message_request(SseDeserializer deserializer);

  @protected
  SilentPaymentAddressDetails sse_decode_box_autoadd_silent_payment_address_details(
    SseDeserializer deserializer,
  );

  @protected
  SparkAddressDetails sse_decode_box_autoadd_spark_address_details(SseDeserializer deserializer);

  @protected
  SparkHtlcDetails sse_decode_box_autoadd_spark_htlc_details(SseDeserializer deserializer);

  @protected
  SparkHtlcOptions sse_decode_box_autoadd_spark_htlc_options(SseDeserializer deserializer);

  @protected
  SparkInvoiceDetails sse_decode_box_autoadd_spark_invoice_details(SseDeserializer deserializer);

  @protected
  SparkInvoicePaymentDetails sse_decode_box_autoadd_spark_invoice_payment_details(
    SseDeserializer deserializer,
  );

  @protected
  SuccessAction sse_decode_box_autoadd_success_action(SseDeserializer deserializer);

  @protected
  SuccessActionProcessed sse_decode_box_autoadd_success_action_processed(SseDeserializer deserializer);

  @protected
  Symbol sse_decode_box_autoadd_symbol(SseDeserializer deserializer);

  @protected
  SyncWalletRequest sse_decode_box_autoadd_sync_wallet_request(SseDeserializer deserializer);

  @protected
  TokenMetadata sse_decode_box_autoadd_token_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UnfreezeIssuerTokenRequest sse_decode_box_autoadd_unfreeze_issuer_token_request(
    SseDeserializer deserializer,
  );

  @protected
  UpdateUserSettingsRequest sse_decode_box_autoadd_update_user_settings_request(SseDeserializer deserializer);

  @protected
  UrlSuccessActionData sse_decode_box_autoadd_url_success_action_data(SseDeserializer deserializer);

  @protected
  BurnIssuerTokenRequest sse_decode_burn_issuer_token_request(SseDeserializer deserializer);

  @protected
  ChainApiType sse_decode_chain_api_type(SseDeserializer deserializer);

  @protected
  CheckLightningAddressRequest sse_decode_check_lightning_address_request(SseDeserializer deserializer);

  @protected
  CheckMessageRequest sse_decode_check_message_request(SseDeserializer deserializer);

  @protected
  CheckMessageResponse sse_decode_check_message_response(SseDeserializer deserializer);

  @protected
  ClaimDepositRequest sse_decode_claim_deposit_request(SseDeserializer deserializer);

  @protected
  ClaimDepositResponse sse_decode_claim_deposit_response(SseDeserializer deserializer);

  @protected
  ClaimHtlcPaymentRequest sse_decode_claim_htlc_payment_request(SseDeserializer deserializer);

  @protected
  ClaimHtlcPaymentResponse sse_decode_claim_htlc_payment_response(SseDeserializer deserializer);

  @protected
  Config sse_decode_config(SseDeserializer deserializer);

  @protected
  ConnectRequest sse_decode_connect_request(SseDeserializer deserializer);

  @protected
  ConversionEstimate sse_decode_conversion_estimate(SseDeserializer deserializer);

  @protected
  ConversionInfo sse_decode_conversion_info(SseDeserializer deserializer);

  @protected
  ConversionOptions sse_decode_conversion_options(SseDeserializer deserializer);

  @protected
  ConversionPurpose sse_decode_conversion_purpose(SseDeserializer deserializer);

  @protected
  ConversionStatus sse_decode_conversion_status(SseDeserializer deserializer);

  @protected
  ConversionType sse_decode_conversion_type(SseDeserializer deserializer);

  @protected
  CreateIssuerTokenRequest sse_decode_create_issuer_token_request(SseDeserializer deserializer);

  @protected
  Credentials sse_decode_credentials(SseDeserializer deserializer);

  @protected
  CurrencyInfo sse_decode_currency_info(SseDeserializer deserializer);

  @protected
  DepositClaimError sse_decode_deposit_claim_error(SseDeserializer deserializer);

  @protected
  DepositInfo sse_decode_deposit_info(SseDeserializer deserializer);

  @protected
  ExternalInputParser sse_decode_external_input_parser(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Fee sse_decode_fee(SseDeserializer deserializer);

  @protected
  FetchConversionLimitsRequest sse_decode_fetch_conversion_limits_request(SseDeserializer deserializer);

  @protected
  FetchConversionLimitsResponse sse_decode_fetch_conversion_limits_response(SseDeserializer deserializer);

  @protected
  FiatCurrency sse_decode_fiat_currency(SseDeserializer deserializer);

  @protected
  FreezeIssuerTokenRequest sse_decode_freeze_issuer_token_request(SseDeserializer deserializer);

  @protected
  FreezeIssuerTokenResponse sse_decode_freeze_issuer_token_response(SseDeserializer deserializer);

  @protected
  GetInfoRequest sse_decode_get_info_request(SseDeserializer deserializer);

  @protected
  GetInfoResponse sse_decode_get_info_response(SseDeserializer deserializer);

  @protected
  GetPaymentRequest sse_decode_get_payment_request(SseDeserializer deserializer);

  @protected
  GetPaymentResponse sse_decode_get_payment_response(SseDeserializer deserializer);

  @protected
  GetTokensMetadataRequest sse_decode_get_tokens_metadata_request(SseDeserializer deserializer);

  @protected
  GetTokensMetadataResponse sse_decode_get_tokens_metadata_response(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InputType sse_decode_input_type(SseDeserializer deserializer);

  @protected
  KeySetConfig sse_decode_key_set_config(SseDeserializer deserializer);

  @protected
  KeySetType sse_decode_key_set_type(SseDeserializer deserializer);

  @protected
  LightningAddressDetails sse_decode_lightning_address_details(SseDeserializer deserializer);

  @protected
  LightningAddressInfo sse_decode_lightning_address_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Bip21Extra> sse_decode_list_bip_21_extra(SseDeserializer deserializer);

  @protected
  List<Bolt11RouteHint> sse_decode_list_bolt_11_route_hint(SseDeserializer deserializer);

  @protected
  List<Bolt11RouteHintHop> sse_decode_list_bolt_11_route_hint_hop(SseDeserializer deserializer);

  @protected
  List<Bolt12OfferBlindedPath> sse_decode_list_bolt_12_offer_blinded_path(SseDeserializer deserializer);

  @protected
  List<DepositInfo> sse_decode_list_deposit_info(SseDeserializer deserializer);

  @protected
  List<ExternalInputParser> sse_decode_list_external_input_parser(SseDeserializer deserializer);

  @protected
  ListFiatCurrenciesResponse sse_decode_list_fiat_currencies_response(SseDeserializer deserializer);

  @protected
  List<FiatCurrency> sse_decode_list_fiat_currency(SseDeserializer deserializer);

  @protected
  ListFiatRatesResponse sse_decode_list_fiat_rates_response(SseDeserializer deserializer);

  @protected
  List<InputType> sse_decode_list_input_type(SseDeserializer deserializer);

  @protected
  List<LocaleOverrides> sse_decode_list_locale_overrides(SseDeserializer deserializer);

  @protected
  List<LocalizedName> sse_decode_list_localized_name(SseDeserializer deserializer);

  @protected
  List<Payment> sse_decode_list_payment(SseDeserializer deserializer);

  @protected
  List<PaymentDetailsFilter> sse_decode_list_payment_details_filter(SseDeserializer deserializer);

  @protected
  List<PaymentStatus> sse_decode_list_payment_status(SseDeserializer deserializer);

  @protected
  List<PaymentType> sse_decode_list_payment_type(SseDeserializer deserializer);

  @protected
  ListPaymentsRequest sse_decode_list_payments_request(SseDeserializer deserializer);

  @protected
  ListPaymentsResponse sse_decode_list_payments_response(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Rate> sse_decode_list_rate(SseDeserializer deserializer);

  @protected
  List<(String, TokenBalance)> sse_decode_list_record_string_token_balance(SseDeserializer deserializer);

  @protected
  List<SparkHtlcStatus> sse_decode_list_spark_htlc_status(SseDeserializer deserializer);

  @protected
  List<TokenMetadata> sse_decode_list_token_metadata(SseDeserializer deserializer);

  @protected
  ListUnclaimedDepositsRequest sse_decode_list_unclaimed_deposits_request(SseDeserializer deserializer);

  @protected
  ListUnclaimedDepositsResponse sse_decode_list_unclaimed_deposits_response(SseDeserializer deserializer);

  @protected
  LnurlAuthRequestDetails sse_decode_lnurl_auth_request_details(SseDeserializer deserializer);

  @protected
  LnurlCallbackStatus sse_decode_lnurl_callback_status(SseDeserializer deserializer);

  @protected
  LnurlErrorDetails sse_decode_lnurl_error_details(SseDeserializer deserializer);

  @protected
  LnurlPayInfo sse_decode_lnurl_pay_info(SseDeserializer deserializer);

  @protected
  LnurlPayRequest sse_decode_lnurl_pay_request(SseDeserializer deserializer);

  @protected
  LnurlPayRequestDetails sse_decode_lnurl_pay_request_details(SseDeserializer deserializer);

  @protected
  LnurlPayResponse sse_decode_lnurl_pay_response(SseDeserializer deserializer);

  @protected
  LnurlReceiveMetadata sse_decode_lnurl_receive_metadata(SseDeserializer deserializer);

  @protected
  LnurlWithdrawInfo sse_decode_lnurl_withdraw_info(SseDeserializer deserializer);

  @protected
  LnurlWithdrawRequest sse_decode_lnurl_withdraw_request(SseDeserializer deserializer);

  @protected
  LnurlWithdrawRequestDetails sse_decode_lnurl_withdraw_request_details(SseDeserializer deserializer);

  @protected
  LnurlWithdrawResponse sse_decode_lnurl_withdraw_response(SseDeserializer deserializer);

  @protected
  LocaleOverrides sse_decode_locale_overrides(SseDeserializer deserializer);

  @protected
  LocalizedName sse_decode_localized_name(SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  MaxFee sse_decode_max_fee(SseDeserializer deserializer);

  @protected
  MessageSuccessActionData sse_decode_message_success_action_data(SseDeserializer deserializer);

  @protected
  MintIssuerTokenRequest sse_decode_mint_issuer_token_request(SseDeserializer deserializer);

  @protected
  Network sse_decode_network(SseDeserializer deserializer);

  @protected
  OnchainConfirmationSpeed sse_decode_onchain_confirmation_speed(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_U128(SseDeserializer deserializer);

  @protected
  Amount? sse_decode_opt_box_autoadd_amount(SseDeserializer deserializer);

  @protected
  AssetFilter? sse_decode_opt_box_autoadd_asset_filter(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ConversionEstimate? sse_decode_opt_box_autoadd_conversion_estimate(SseDeserializer deserializer);

  @protected
  ConversionInfo? sse_decode_opt_box_autoadd_conversion_info(SseDeserializer deserializer);

  @protected
  ConversionOptions? sse_decode_opt_box_autoadd_conversion_options(SseDeserializer deserializer);

  @protected
  ConversionPurpose? sse_decode_opt_box_autoadd_conversion_purpose(SseDeserializer deserializer);

  @protected
  Credentials? sse_decode_opt_box_autoadd_credentials(SseDeserializer deserializer);

  @protected
  DepositClaimError? sse_decode_opt_box_autoadd_deposit_claim_error(SseDeserializer deserializer);

  @protected
  Fee? sse_decode_opt_box_autoadd_fee(SseDeserializer deserializer);

  @protected
  LightningAddressInfo? sse_decode_opt_box_autoadd_lightning_address_info(SseDeserializer deserializer);

  @protected
  LnurlPayInfo? sse_decode_opt_box_autoadd_lnurl_pay_info(SseDeserializer deserializer);

  @protected
  LnurlReceiveMetadata? sse_decode_opt_box_autoadd_lnurl_receive_metadata(SseDeserializer deserializer);

  @protected
  LnurlWithdrawInfo? sse_decode_opt_box_autoadd_lnurl_withdraw_info(SseDeserializer deserializer);

  @protected
  MaxFee? sse_decode_opt_box_autoadd_max_fee(SseDeserializer deserializer);

  @protected
  Payment? sse_decode_opt_box_autoadd_payment(SseDeserializer deserializer);

  @protected
  PaymentDetails? sse_decode_opt_box_autoadd_payment_details(SseDeserializer deserializer);

  @protected
  SendPaymentOptions? sse_decode_opt_box_autoadd_send_payment_options(SseDeserializer deserializer);

  @protected
  SparkHtlcDetails? sse_decode_opt_box_autoadd_spark_htlc_details(SseDeserializer deserializer);

  @protected
  SparkHtlcOptions? sse_decode_opt_box_autoadd_spark_htlc_options(SseDeserializer deserializer);

  @protected
  SparkInvoicePaymentDetails? sse_decode_opt_box_autoadd_spark_invoice_payment_details(
    SseDeserializer deserializer,
  );

  @protected
  SuccessAction? sse_decode_opt_box_autoadd_success_action(SseDeserializer deserializer);

  @protected
  SuccessActionProcessed? sse_decode_opt_box_autoadd_success_action_processed(SseDeserializer deserializer);

  @protected
  Symbol? sse_decode_opt_box_autoadd_symbol(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<ExternalInputParser>? sse_decode_opt_list_external_input_parser(SseDeserializer deserializer);

  @protected
  List<PaymentDetailsFilter>? sse_decode_opt_list_payment_details_filter(SseDeserializer deserializer);

  @protected
  List<PaymentStatus>? sse_decode_opt_list_payment_status(SseDeserializer deserializer);

  @protected
  List<PaymentType>? sse_decode_opt_list_payment_type(SseDeserializer deserializer);

  @protected
  List<SparkHtlcStatus>? sse_decode_opt_list_spark_htlc_status(SseDeserializer deserializer);

  @protected
  OptimizationConfig sse_decode_optimization_config(SseDeserializer deserializer);

  @protected
  OptimizationEvent sse_decode_optimization_event(SseDeserializer deserializer);

  @protected
  OptimizationProgress sse_decode_optimization_progress(SseDeserializer deserializer);

  @protected
  Payment sse_decode_payment(SseDeserializer deserializer);

  @protected
  PaymentDetails sse_decode_payment_details(SseDeserializer deserializer);

  @protected
  PaymentDetailsFilter sse_decode_payment_details_filter(SseDeserializer deserializer);

  @protected
  PaymentMethod sse_decode_payment_method(SseDeserializer deserializer);

  @protected
  PaymentRequestSource sse_decode_payment_request_source(SseDeserializer deserializer);

  @protected
  PaymentStatus sse_decode_payment_status(SseDeserializer deserializer);

  @protected
  PaymentType sse_decode_payment_type(SseDeserializer deserializer);

  @protected
  PrepareLnurlPayRequest sse_decode_prepare_lnurl_pay_request(SseDeserializer deserializer);

  @protected
  PrepareLnurlPayResponse sse_decode_prepare_lnurl_pay_response(SseDeserializer deserializer);

  @protected
  PrepareSendPaymentRequest sse_decode_prepare_send_payment_request(SseDeserializer deserializer);

  @protected
  PrepareSendPaymentResponse sse_decode_prepare_send_payment_response(SseDeserializer deserializer);

  @protected
  Rate sse_decode_rate(SseDeserializer deserializer);

  @protected
  ReceivePaymentMethod sse_decode_receive_payment_method(SseDeserializer deserializer);

  @protected
  ReceivePaymentRequest sse_decode_receive_payment_request(SseDeserializer deserializer);

  @protected
  ReceivePaymentResponse sse_decode_receive_payment_response(SseDeserializer deserializer);

  @protected
  RecommendedFees sse_decode_recommended_fees(SseDeserializer deserializer);

  @protected
  (String, TokenBalance) sse_decode_record_string_token_balance(SseDeserializer deserializer);

  @protected
  RefundDepositRequest sse_decode_refund_deposit_request(SseDeserializer deserializer);

  @protected
  RefundDepositResponse sse_decode_refund_deposit_response(SseDeserializer deserializer);

  @protected
  RegisterLightningAddressRequest sse_decode_register_lightning_address_request(SseDeserializer deserializer);

  @protected
  SdkError sse_decode_sdk_error(SseDeserializer deserializer);

  @protected
  SdkEvent sse_decode_sdk_event(SseDeserializer deserializer);

  @protected
  Seed sse_decode_seed(SseDeserializer deserializer);

  @protected
  SendOnchainFeeQuote sse_decode_send_onchain_fee_quote(SseDeserializer deserializer);

  @protected
  SendOnchainSpeedFeeQuote sse_decode_send_onchain_speed_fee_quote(SseDeserializer deserializer);

  @protected
  SendPaymentMethod sse_decode_send_payment_method(SseDeserializer deserializer);

  @protected
  SendPaymentOptions sse_decode_send_payment_options(SseDeserializer deserializer);

  @protected
  SendPaymentRequest sse_decode_send_payment_request(SseDeserializer deserializer);

  @protected
  SendPaymentResponse sse_decode_send_payment_response(SseDeserializer deserializer);

  @protected
  SignMessageRequest sse_decode_sign_message_request(SseDeserializer deserializer);

  @protected
  SignMessageResponse sse_decode_sign_message_response(SseDeserializer deserializer);

  @protected
  SilentPaymentAddressDetails sse_decode_silent_payment_address_details(SseDeserializer deserializer);

  @protected
  SparkAddressDetails sse_decode_spark_address_details(SseDeserializer deserializer);

  @protected
  SparkHtlcDetails sse_decode_spark_htlc_details(SseDeserializer deserializer);

  @protected
  SparkHtlcOptions sse_decode_spark_htlc_options(SseDeserializer deserializer);

  @protected
  SparkHtlcStatus sse_decode_spark_htlc_status(SseDeserializer deserializer);

  @protected
  SparkInvoiceDetails sse_decode_spark_invoice_details(SseDeserializer deserializer);

  @protected
  SparkInvoicePaymentDetails sse_decode_spark_invoice_payment_details(SseDeserializer deserializer);

  @protected
  SuccessAction sse_decode_success_action(SseDeserializer deserializer);

  @protected
  SuccessActionProcessed sse_decode_success_action_processed(SseDeserializer deserializer);

  @protected
  Symbol sse_decode_symbol(SseDeserializer deserializer);

  @protected
  SyncWalletRequest sse_decode_sync_wallet_request(SseDeserializer deserializer);

  @protected
  SyncWalletResponse sse_decode_sync_wallet_response(SseDeserializer deserializer);

  @protected
  TokenBalance sse_decode_token_balance(SseDeserializer deserializer);

  @protected
  TokenMetadata sse_decode_token_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UnfreezeIssuerTokenRequest sse_decode_unfreeze_issuer_token_request(SseDeserializer deserializer);

  @protected
  UnfreezeIssuerTokenResponse sse_decode_unfreeze_issuer_token_response(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateUserSettingsRequest sse_decode_update_user_settings_request(SseDeserializer deserializer);

  @protected
  UrlSuccessActionData sse_decode_url_success_action_data(SseDeserializer deserializer);

  @protected
  UserSettings sse_decode_user_settings(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    BreezSdk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SdkBuilder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    TokenIssuer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    BreezSdk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SdkBuilder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    TokenIssuer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_token_balance_None(Map<String, TokenBalance> self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    BreezSdk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    SdkBuilder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    TokenIssuer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(RustStreamSink<LogEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_sdk_event_Sse(RustStreamSink<SdkEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_aes_success_action_data(AesSuccessActionData self, SseSerializer serializer);

  @protected
  void sse_encode_aes_success_action_data_decrypted(
    AesSuccessActionDataDecrypted self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_aes_success_action_data_result(AesSuccessActionDataResult self, SseSerializer serializer);

  @protected
  void sse_encode_amount(Amount self, SseSerializer serializer);

  @protected
  void sse_encode_asset_filter(AssetFilter self, SseSerializer serializer);

  @protected
  void sse_encode_bip_21_details(Bip21Details self, SseSerializer serializer);

  @protected
  void sse_encode_bip_21_extra(Bip21Extra self, SseSerializer serializer);

  @protected
  void sse_encode_bitcoin_address_details(BitcoinAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_bitcoin_network(BitcoinNetwork self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_11_invoice(Bolt11Invoice self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_11_invoice_details(Bolt11InvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_11_route_hint(Bolt11RouteHint self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_11_route_hint_hop(Bolt11RouteHintHop self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_invoice(Bolt12Invoice self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_invoice_details(Bolt12InvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_invoice_request_details(Bolt12InvoiceRequestDetails self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_offer(Bolt12Offer self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_offer_blinded_path(Bolt12OfferBlindedPath self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_offer_details(Bolt12OfferDetails self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_aes_success_action_data(AesSuccessActionData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_aes_success_action_data_decrypted(
    AesSuccessActionDataDecrypted self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_aes_success_action_data_result(
    AesSuccessActionDataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_amount(Amount self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_asset_filter(AssetFilter self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bip_21_details(Bip21Details self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bitcoin_address_details(BitcoinAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bolt_11_invoice_details(Bolt11InvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bolt_12_invoice_details(Bolt12InvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bolt_12_invoice_request_details(
    Bolt12InvoiceRequestDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bolt_12_offer_details(Bolt12OfferDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_burn_issuer_token_request(
    BurnIssuerTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_check_lightning_address_request(
    CheckLightningAddressRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_check_message_request(CheckMessageRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_claim_deposit_request(ClaimDepositRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_claim_htlc_payment_request(
    ClaimHtlcPaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_connect_request(ConnectRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversion_estimate(ConversionEstimate self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversion_info(ConversionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversion_options(ConversionOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversion_purpose(ConversionPurpose self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_issuer_token_request(
    CreateIssuerTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_credentials(Credentials self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_deposit_claim_error(DepositClaimError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fee(Fee self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fetch_conversion_limits_request(
    FetchConversionLimitsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_freeze_issuer_token_request(
    FreezeIssuerTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_get_info_request(GetInfoRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_get_payment_request(GetPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_get_tokens_metadata_request(
    GetTokensMetadataRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_key_set_config(KeySetConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lightning_address_details(
    LightningAddressDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lightning_address_info(LightningAddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_list_payments_request(ListPaymentsRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_list_unclaimed_deposits_request(
    ListUnclaimedDepositsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lnurl_auth_request_details(
    LnurlAuthRequestDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lnurl_error_details(LnurlErrorDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_pay_info(LnurlPayInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_pay_request(LnurlPayRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_pay_request_details(
    LnurlPayRequestDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lnurl_receive_metadata(LnurlReceiveMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_withdraw_info(LnurlWithdrawInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_withdraw_request(LnurlWithdrawRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lnurl_withdraw_request_details(
    LnurlWithdrawRequestDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_max_fee(MaxFee self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_success_action_data(
    MessageSuccessActionData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mint_issuer_token_request(
    MintIssuerTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_optimization_event(OptimizationEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_payment(Payment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_payment_details(PaymentDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_prepare_lnurl_pay_request(
    PrepareLnurlPayRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_prepare_send_payment_request(
    PrepareSendPaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_receive_payment_request(ReceivePaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_refund_deposit_request(RefundDepositRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_register_lightning_address_request(
    RegisterLightningAddressRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_seed(Seed self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_send_onchain_fee_quote(SendOnchainFeeQuote self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_send_payment_options(SendPaymentOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_send_payment_request(SendPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sign_message_request(SignMessageRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_silent_payment_address_details(
    SilentPaymentAddressDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_spark_address_details(SparkAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spark_htlc_details(SparkHtlcDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spark_htlc_options(SparkHtlcOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spark_invoice_details(SparkInvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spark_invoice_payment_details(
    SparkInvoicePaymentDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_success_action(SuccessAction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_success_action_processed(SuccessActionProcessed self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_symbol(Symbol self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_wallet_request(SyncWalletRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_token_metadata(TokenMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_unfreeze_issuer_token_request(
    UnfreezeIssuerTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_update_user_settings_request(
    UpdateUserSettingsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_url_success_action_data(UrlSuccessActionData self, SseSerializer serializer);

  @protected
  void sse_encode_burn_issuer_token_request(BurnIssuerTokenRequest self, SseSerializer serializer);

  @protected
  void sse_encode_chain_api_type(ChainApiType self, SseSerializer serializer);

  @protected
  void sse_encode_check_lightning_address_request(
    CheckLightningAddressRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_check_message_request(CheckMessageRequest self, SseSerializer serializer);

  @protected
  void sse_encode_check_message_response(CheckMessageResponse self, SseSerializer serializer);

  @protected
  void sse_encode_claim_deposit_request(ClaimDepositRequest self, SseSerializer serializer);

  @protected
  void sse_encode_claim_deposit_response(ClaimDepositResponse self, SseSerializer serializer);

  @protected
  void sse_encode_claim_htlc_payment_request(ClaimHtlcPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_claim_htlc_payment_response(ClaimHtlcPaymentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_connect_request(ConnectRequest self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_estimate(ConversionEstimate self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_info(ConversionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_options(ConversionOptions self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_purpose(ConversionPurpose self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_status(ConversionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_type(ConversionType self, SseSerializer serializer);

  @protected
  void sse_encode_create_issuer_token_request(CreateIssuerTokenRequest self, SseSerializer serializer);

  @protected
  void sse_encode_credentials(Credentials self, SseSerializer serializer);

  @protected
  void sse_encode_currency_info(CurrencyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_deposit_claim_error(DepositClaimError self, SseSerializer serializer);

  @protected
  void sse_encode_deposit_info(DepositInfo self, SseSerializer serializer);

  @protected
  void sse_encode_external_input_parser(ExternalInputParser self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee(Fee self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_conversion_limits_request(
    FetchConversionLimitsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fetch_conversion_limits_response(
    FetchConversionLimitsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fiat_currency(FiatCurrency self, SseSerializer serializer);

  @protected
  void sse_encode_freeze_issuer_token_request(FreezeIssuerTokenRequest self, SseSerializer serializer);

  @protected
  void sse_encode_freeze_issuer_token_response(FreezeIssuerTokenResponse self, SseSerializer serializer);

  @protected
  void sse_encode_get_info_request(GetInfoRequest self, SseSerializer serializer);

  @protected
  void sse_encode_get_info_response(GetInfoResponse self, SseSerializer serializer);

  @protected
  void sse_encode_get_payment_request(GetPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_get_payment_response(GetPaymentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_get_tokens_metadata_request(GetTokensMetadataRequest self, SseSerializer serializer);

  @protected
  void sse_encode_get_tokens_metadata_response(GetTokensMetadataResponse self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_input_type(InputType self, SseSerializer serializer);

  @protected
  void sse_encode_key_set_config(KeySetConfig self, SseSerializer serializer);

  @protected
  void sse_encode_key_set_type(KeySetType self, SseSerializer serializer);

  @protected
  void sse_encode_lightning_address_details(LightningAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_lightning_address_info(LightningAddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bip_21_extra(List<Bip21Extra> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bolt_11_route_hint(List<Bolt11RouteHint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bolt_11_route_hint_hop(List<Bolt11RouteHintHop> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bolt_12_offer_blinded_path(
    List<Bolt12OfferBlindedPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_deposit_info(List<DepositInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_external_input_parser(List<ExternalInputParser> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fiat_currencies_response(ListFiatCurrenciesResponse self, SseSerializer serializer);

  @protected
  void sse_encode_list_fiat_currency(List<FiatCurrency> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fiat_rates_response(ListFiatRatesResponse self, SseSerializer serializer);

  @protected
  void sse_encode_list_input_type(List<InputType> self, SseSerializer serializer);

  @protected
  void sse_encode_list_locale_overrides(List<LocaleOverrides> self, SseSerializer serializer);

  @protected
  void sse_encode_list_localized_name(List<LocalizedName> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment(List<Payment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_details_filter(List<PaymentDetailsFilter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_status(List<PaymentStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_type(List<PaymentType> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payments_request(ListPaymentsRequest self, SseSerializer serializer);

  @protected
  void sse_encode_list_payments_response(ListPaymentsResponse self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_rate(List<Rate> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_token_balance(
    List<(String, TokenBalance)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_spark_htlc_status(List<SparkHtlcStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_list_token_metadata(List<TokenMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_list_unclaimed_deposits_request(
    ListUnclaimedDepositsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unclaimed_deposits_response(
    ListUnclaimedDepositsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lnurl_auth_request_details(LnurlAuthRequestDetails self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_callback_status(LnurlCallbackStatus self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_error_details(LnurlErrorDetails self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_pay_info(LnurlPayInfo self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_pay_request(LnurlPayRequest self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_pay_request_details(LnurlPayRequestDetails self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_pay_response(LnurlPayResponse self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_receive_metadata(LnurlReceiveMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_withdraw_info(LnurlWithdrawInfo self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_withdraw_request(LnurlWithdrawRequest self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_withdraw_request_details(LnurlWithdrawRequestDetails self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_withdraw_response(LnurlWithdrawResponse self, SseSerializer serializer);

  @protected
  void sse_encode_locale_overrides(LocaleOverrides self, SseSerializer serializer);

  @protected
  void sse_encode_localized_name(LocalizedName self, SseSerializer serializer);

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_max_fee(MaxFee self, SseSerializer serializer);

  @protected
  void sse_encode_message_success_action_data(MessageSuccessActionData self, SseSerializer serializer);

  @protected
  void sse_encode_mint_issuer_token_request(MintIssuerTokenRequest self, SseSerializer serializer);

  @protected
  void sse_encode_network(Network self, SseSerializer serializer);

  @protected
  void sse_encode_onchain_confirmation_speed(OnchainConfirmationSpeed self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_U128(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_amount(Amount? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_asset_filter(AssetFilter? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversion_estimate(ConversionEstimate? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversion_info(ConversionInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversion_options(ConversionOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversion_purpose(ConversionPurpose? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_credentials(Credentials? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_deposit_claim_error(DepositClaimError? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fee(Fee? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lightning_address_info(
    LightningAddressInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_lnurl_pay_info(LnurlPayInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lnurl_receive_metadata(
    LnurlReceiveMetadata? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_lnurl_withdraw_info(LnurlWithdrawInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_max_fee(MaxFee? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_payment(Payment? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_payment_details(PaymentDetails? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_send_payment_options(SendPaymentOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_spark_htlc_details(SparkHtlcDetails? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_spark_htlc_options(SparkHtlcOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_spark_invoice_payment_details(
    SparkInvoicePaymentDetails? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_success_action(SuccessAction? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_success_action_processed(
    SuccessActionProcessed? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_symbol(Symbol? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_external_input_parser(List<ExternalInputParser>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_payment_details_filter(List<PaymentDetailsFilter>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_payment_status(List<PaymentStatus>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_payment_type(List<PaymentType>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_spark_htlc_status(List<SparkHtlcStatus>? self, SseSerializer serializer);

  @protected
  void sse_encode_optimization_config(OptimizationConfig self, SseSerializer serializer);

  @protected
  void sse_encode_optimization_event(OptimizationEvent self, SseSerializer serializer);

  @protected
  void sse_encode_optimization_progress(OptimizationProgress self, SseSerializer serializer);

  @protected
  void sse_encode_payment(Payment self, SseSerializer serializer);

  @protected
  void sse_encode_payment_details(PaymentDetails self, SseSerializer serializer);

  @protected
  void sse_encode_payment_details_filter(PaymentDetailsFilter self, SseSerializer serializer);

  @protected
  void sse_encode_payment_method(PaymentMethod self, SseSerializer serializer);

  @protected
  void sse_encode_payment_request_source(PaymentRequestSource self, SseSerializer serializer);

  @protected
  void sse_encode_payment_status(PaymentStatus self, SseSerializer serializer);

  @protected
  void sse_encode_payment_type(PaymentType self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_lnurl_pay_request(PrepareLnurlPayRequest self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_lnurl_pay_response(PrepareLnurlPayResponse self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_send_payment_request(PrepareSendPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_send_payment_response(PrepareSendPaymentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_rate(Rate self, SseSerializer serializer);

  @protected
  void sse_encode_receive_payment_method(ReceivePaymentMethod self, SseSerializer serializer);

  @protected
  void sse_encode_receive_payment_request(ReceivePaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_receive_payment_response(ReceivePaymentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_recommended_fees(RecommendedFees self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_token_balance((String, TokenBalance) self, SseSerializer serializer);

  @protected
  void sse_encode_refund_deposit_request(RefundDepositRequest self, SseSerializer serializer);

  @protected
  void sse_encode_refund_deposit_response(RefundDepositResponse self, SseSerializer serializer);

  @protected
  void sse_encode_register_lightning_address_request(
    RegisterLightningAddressRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sdk_error(SdkError self, SseSerializer serializer);

  @protected
  void sse_encode_sdk_event(SdkEvent self, SseSerializer serializer);

  @protected
  void sse_encode_seed(Seed self, SseSerializer serializer);

  @protected
  void sse_encode_send_onchain_fee_quote(SendOnchainFeeQuote self, SseSerializer serializer);

  @protected
  void sse_encode_send_onchain_speed_fee_quote(SendOnchainSpeedFeeQuote self, SseSerializer serializer);

  @protected
  void sse_encode_send_payment_method(SendPaymentMethod self, SseSerializer serializer);

  @protected
  void sse_encode_send_payment_options(SendPaymentOptions self, SseSerializer serializer);

  @protected
  void sse_encode_send_payment_request(SendPaymentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_send_payment_response(SendPaymentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_sign_message_request(SignMessageRequest self, SseSerializer serializer);

  @protected
  void sse_encode_sign_message_response(SignMessageResponse self, SseSerializer serializer);

  @protected
  void sse_encode_silent_payment_address_details(SilentPaymentAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_spark_address_details(SparkAddressDetails self, SseSerializer serializer);

  @protected
  void sse_encode_spark_htlc_details(SparkHtlcDetails self, SseSerializer serializer);

  @protected
  void sse_encode_spark_htlc_options(SparkHtlcOptions self, SseSerializer serializer);

  @protected
  void sse_encode_spark_htlc_status(SparkHtlcStatus self, SseSerializer serializer);

  @protected
  void sse_encode_spark_invoice_details(SparkInvoiceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_spark_invoice_payment_details(SparkInvoicePaymentDetails self, SseSerializer serializer);

  @protected
  void sse_encode_success_action(SuccessAction self, SseSerializer serializer);

  @protected
  void sse_encode_success_action_processed(SuccessActionProcessed self, SseSerializer serializer);

  @protected
  void sse_encode_symbol(Symbol self, SseSerializer serializer);

  @protected
  void sse_encode_sync_wallet_request(SyncWalletRequest self, SseSerializer serializer);

  @protected
  void sse_encode_sync_wallet_response(SyncWalletResponse self, SseSerializer serializer);

  @protected
  void sse_encode_token_balance(TokenBalance self, SseSerializer serializer);

  @protected
  void sse_encode_token_metadata(TokenMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unfreeze_issuer_token_request(UnfreezeIssuerTokenRequest self, SseSerializer serializer);

  @protected
  void sse_encode_unfreeze_issuer_token_response(UnfreezeIssuerTokenResponse self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_user_settings_request(UpdateUserSettingsRequest self, SseSerializer serializer);

  @protected
  void sse_encode_url_success_action_data(UrlSuccessActionData self, SseSerializer serializer);

  @protected
  void sse_encode_user_settings(UserSettings self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class BreezSdkSparkLibWire implements BaseWire {
  factory BreezSdkSparkLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      BreezSdkSparkLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BreezSdkSparkLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdk =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBreezSdkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSdkBuilderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_breez_sdk_spark_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuer =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenIssuerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
