// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< TokenIssuer>>
abstract class TokenIssuer implements RustOpaqueInterface {
  Future<Payment> burnIssuerToken({required BurnIssuerTokenRequest request});

  Future<TokenMetadata> createIssuerToken({required CreateIssuerTokenRequest request});

  Future<FreezeIssuerTokenResponse> freezeIssuerToken({required FreezeIssuerTokenRequest request});

  Future<TokenBalance> getIssuerTokenBalance();

  Future<TokenMetadata> getIssuerTokenMetadata();

  Future<Payment> mintIssuerToken({required MintIssuerTokenRequest request});

  Future<UnfreezeIssuerTokenResponse> unfreezeIssuerToken({required UnfreezeIssuerTokenRequest request});
}
