// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'events.dart';
import 'frb_generated.dart';
import 'issuer.dart';
import 'logger.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BreezSdk> connect({required ConnectRequest request}) =>
    BreezSdkSparkLib.instance.api.crateSdkConnect(request: request);

Config defaultConfig({required Network network}) =>
    BreezSdkSparkLib.instance.api.crateSdkDefaultConfig(network: network);

Stream<LogEntry> initLogging({String? logDir, String? logFilter}) =>
    BreezSdkSparkLib.instance.api.crateSdkInitLogging(logDir: logDir, logFilter: logFilter);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BreezSdk>>
abstract class BreezSdk implements RustOpaqueInterface {
  Stream<SdkEvent> addEventListener();

  Future<void> cancelLeafOptimization();

  Future<bool> checkLightningAddressAvailable({required CheckLightningAddressRequest request});

  Future<CheckMessageResponse> checkMessage({required CheckMessageRequest request});

  Future<ClaimDepositResponse> claimDeposit({required ClaimDepositRequest request});

  Future<ClaimHtlcPaymentResponse> claimHtlcPayment({required ClaimHtlcPaymentRequest request});

  Future<void> deleteLightningAddress();

  Future<void> disconnect();

  Future<FetchConversionLimitsResponse> fetchConversionLimits({
    required FetchConversionLimitsRequest request,
  });

  Future<GetInfoResponse> getInfo({required GetInfoRequest request});

  OptimizationProgress getLeafOptimizationProgress();

  Future<LightningAddressInfo?> getLightningAddress();

  Future<GetPaymentResponse> getPayment({required GetPaymentRequest request});

  TokenIssuer getTokenIssuer();

  Future<GetTokensMetadataResponse> getTokensMetadata({required GetTokensMetadataRequest request});

  Future<UserSettings> getUserSettings();

  Future<ListFiatCurrenciesResponse> listFiatCurrencies();

  Future<ListFiatRatesResponse> listFiatRates();

  Future<ListPaymentsResponse> listPayments({required ListPaymentsRequest request});

  Future<ListUnclaimedDepositsResponse> listUnclaimedDeposits({
    required ListUnclaimedDepositsRequest request,
  });

  Future<LnurlCallbackStatus> lnurlAuth({required LnurlAuthRequestDetails requestData});

  Future<LnurlPayResponse> lnurlPay({required LnurlPayRequest request});

  Future<LnurlWithdrawResponse> lnurlWithdraw({required LnurlWithdrawRequest request});

  Future<InputType> parse({required String input});

  Future<PrepareLnurlPayResponse> prepareLnurlPay({required PrepareLnurlPayRequest request});

  Future<PrepareSendPaymentResponse> prepareSendPayment({required PrepareSendPaymentRequest request});

  Future<ReceivePaymentResponse> receivePayment({required ReceivePaymentRequest request});

  Future<RecommendedFees> recommendedFees();

  Future<RefundDepositResponse> refundDeposit({required RefundDepositRequest request});

  Future<LightningAddressInfo> registerLightningAddress({required RegisterLightningAddressRequest request});

  Future<bool> removeEventListener({required String id});

  Future<SendPaymentResponse> sendPayment({required SendPaymentRequest request});

  Future<SignMessageResponse> signMessage({required SignMessageRequest request});

  void startLeafOptimization();

  Future<SyncWalletResponse> syncWallet({required SyncWalletRequest request});

  Future<void> updateUserSettings({required UpdateUserSettingsRequest request});
}
