// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sdk.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkBuilder>>
abstract class SdkBuilder implements RustOpaqueInterface {
  Future<BreezSdk> build();

  factory SdkBuilder({required Config config, required Seed seed}) =>
      BreezSdkSparkLib.instance.api.crateSdkBuilderSdkBuilderNew(config: config, seed: seed);

  SdkBuilder withDefaultStorage({required String storageDir});

  SdkBuilder withKeySet({required KeySetConfig config});

  SdkBuilder withRestChainService({
    required String url,
    required ChainApiType apiType,
    Credentials? credentials,
  });
}
